services:
  jenkins:
    image: harshgajjar02/jenkins:custom
    stop_grace_period: 2m
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: {}
